#include "Instructions/ADC.h"
#include "Instructions/AND.h"
#include "Instructions/ASL.h"
#include "Instructions/BCC.h"
#include "Instructions/BCS.h"
#include "Instructions/BIT.h"
#include "Instructions/BMI.h"