#pragma once

//OC_OPCODE_ADDRESSING
enum OpCodes {
    // ADC
    OC_ADC_IMMEDIATE = 0x69,
    OC_ADC_ZERO_PAGE = 0x65,
    OC_ADC_ZERO_PAGE_X = 0x75,
    OC_ADC_ABSOLUTE = 0x6D,
    OC_ADC_ABSOLUTE_X = 0x7D,
    OC_ADC_ABSOLUTE_Y = 0x79,
    OC_ADC_INDIRECT_X = 0x61,
    OC_ADC_INDIRECT_Y = 0x71,
    // AND - Logical AND
    OC_AND_IMMEDIATE = 0x29,
    OC_AND_ZERO_PAGE = 0x25,
    OC_AND_ZERO_PAGE_X = 0x35,
    OC_AND_ABSOLUTE = 0x2D,
    OC_AND_ABSOLUTE_X = 0x3D,
    OC_AND_ABSOLUTE_Y = 0x39,
    OC_AND_INDIRECT_X = 0x21,
    OC_AND_INDIRECT_Y = 0x31,
};